# Generated by Django 5.1.11 on 2026-07-11 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('committed', 'Committed'), ('discarded', 'Discarded')], default='staged', max_length=10)),
                ('fx_rates', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='expenses.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw', models.JSONField()),
                ('parsed', models.JSONField(default=dict)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('settlement', 'Settlement'), ('skip', 'Skip')], default='expense', max_length=12)),
                ('needs_review', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
                ('created_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expense')),
                ('created_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.settlement')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('review', 'Review')], max_length=8)),
                ('message', models.TextField()),
                ('proposed_action', models.JSONField()),
                ('resolved_action', models.JSONField(blank=True, null=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importrow')),
            ],
            options={
                'ordering': ['row__row_number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_row_per_batch'),
        ),
    ]
